# -*- coding: utf-8 -*-
"""datetime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qxhJwHgnHw5qgsHqqV5Xf9tWy2u90CAV
"""

from datetime import datetime

dt_now = datetime.now()
print(dt_now.strftime('%d.%m.%Y'))

from datetime import timedelta

delta = timedelta(days=1)
dt_yesterday = dt_now - delta
print(dt_yesterday.strftime('%d.%m.%Y'))

delta = timedelta(days=1)
dt_month_before = dt_now - delta*30
print(dt_month_before.strftime('%d.%m.%Y'))

dt_month_before = dt_now.replace(month=dt_now.month - 1)
print(dt_month_before.strftime('%d.%m.%Y'))

date_string = "01/01/17 12:10:03.234567"
date_dt = datetime.strptime(date_string, '%d/%m/%y %H:%M:%S.%f')
print(date_dt)